# Generated by Django 5.0.3 on 2024-05-26 14:54

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        default="", verbose_name="Project's description"
                    ),
                ),
                (
                    "technologies",
                    wagtail.fields.StreamField(
                        [("Technology", wagtail.blocks.CharBlock())]
                    ),
                ),
                (
                    "website_link",
                    models.URLField(
                        default=None, null=True, verbose_name="Projet website's link"
                    ),
                ),
                (
                    "repo_link",
                    models.URLField(
                        default=None, null=True, verbose_name="Projet repo's link"
                    ),
                ),
                (
                    "show_on_home_page",
                    models.BooleanField(
                        default=False, verbose_name="Show this project on the home page"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
