# Generated by Django 5.0.3 on 2024-06-19 16:50

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='repo_link',
            field=models.URLField(blank=True, default=None, null=True, verbose_name="Projet repo's link"),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='technologies',
            field=wagtail.fields.StreamField([('Technology', wagtail.blocks.CharBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='website_link',
            field=models.URLField(blank=True, default=None, null=True, verbose_name="Projet website's link"),
        ),
    ]
