# Generated by Django 5.0.3 on 2024-06-26 13:01

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_projectpage_repo_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectpage",
            name="short_description",
            field=wagtail.fields.RichTextField(
                default="",
                verbose_name="Project's short description, to show on list item",
            ),
        ),
    ]
