# Generated by Django 5.0.3 on 2024-07-11 13:47

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_alter_projectpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectpage",
            name="website_link",
        ),
        migrations.AddField(
            model_name="projectpage",
            name="links",
            field=wagtail.fields.StreamField(
                [("Link", wagtail.blocks.URLBlock())], blank=True, null=True
            ),
        ),
    ]
