# Generated by Django 5.0.7 on 2024-08-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0008_alter_projectpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectpage",
            name="image_alt",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
