version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_root_user_password
      POSTGRES_USER: gerg_db_admin
      POSTGRES_DB: postgres
    secrets:
      - db_root_user_password
    volumes:
      - type: bind
        source:  ./dev-db
        target: /var/lib/postgresql/data
      - type: bind
        source:  ./db
        target: /var/lib/postgresql/sql_script
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

secrets:
   db_root_user_password:
     file: secrets/db_root_user_password.txt