services: 
  caddy:
    image: caddy:2.11.2
    container_name: caddy
    restart: always
    ports:
      - 80:80  # Needed for the ACME HTTP-01 challenge.
      - 443:443
      - 443:443/udp # Needed for HTTP/3.
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-config:/config
      - ./caddy-data:/data
      # - ./gregoirelayet/media:/srv/media
      - ./gregoirelayet/ssg:/srv/ssg
      - ./gregoirelayet/enora:/srv/enora
    environment:
      DEPLOYEMENT_USER: "${DEPLOYEMENT_USER}"
      EMAIL: "acme@gregoirelayet.com"                 # The email address to use for ACME registration.
      VW_LOG_FILE: "/data/vw_access.log"
      VAULTWARDEN_FQDN: "${VAULTWARDEN_FQDN}"

  medama:
      image: ghcr.io/medama-io/medama:latest
      container_name: medama
      restart: always
      volumes:
          - medama-data:/app/data
      environment:
        CORS_ALLOWED_ORIGINS: "analytics.gregoirelayet.com,gregoirelayet.com"

  vaultwarden:
    image: vaultwarden/server:1.35.7
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: "https://${VAULTWARDEN_FQDN}"
      SIGNUPS_ALLOWED: "false"
      LOG_FILE: "/data/vaultwarden.log"
      LOG_LEVEL: "warn"
      EXTENDED_LOGGING: "true"
      PUSH_ENABLED: "true"
      PUSH_INSTALLATION_ID: "${VAULTWARDEN_PUSH_INSTALLATION_ID}"
      PUSH_INSTALLATION_KEY: "${VAULTWARDEN_PUSH_INSTALLATION_KEY}"
      SMTP_HOST: "${EMAIL_HOST}"
      SMTP_FROM: "${EMAIL_HOST_USER}"
      SMTP_PORT: "${EMAIL_PORT}"
      SMTP_SECURITY: starttls
      SMTP_USERNAME: "${EMAIL_HOST_USER}"
      SMTP_PASSWORD: "${EMAIL_HOST_PASSWORD}"
    volumes:
      - ./vw-data:/data

  miniflux:
    image: miniflux/miniflux:2.2.19
    restart: always
    depends_on:
      miniflux-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://${MINIFLUX_DB_USER}:${MINIFLUX_DB_PASSWORD}@miniflux-db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1

  miniflux-db:
    image: postgres:18
    restart: always
    environment:
      - POSTGRES_USER=${MINIFLUX_DB_USER}
      - POSTGRES_PASSWORD=${MINIFLUX_DB_PASSWORD}
      - POSTGRES_DB=miniflux
    volumes:
      # You may have to adjust the volume path depending on the version of Postgres
      # Postgres 18 uses /var/lib/postgresql
      # Postgres 17 and below uses /var/lib/postgresql/data
      # See https://hub.docker.com/_/postgres#pgdata
      - miniflux-db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
 

volumes:
  medama-data:
  miniflux-db-data: