---
- name: Retrieve db and statics files from gregoirelayet
  hosts: all
  remote_user: ubuntu
  become: true
  gather_facts: False

  vars_files: ../vars/main.yaml

  tasks:
    - name: Get current date and time
      command: date +"%Y-%m-%d_%H-%M-%S"
      register: current_datetime
      delegate_to: localhost
      become: false

    - name: Dump the database
      become: true
      become_user: "{{ deployement_user }}"
      ansible.builtin.shell:
        chdir: /home/{{ deployement_user }}/
        cmd: docker exec -t gerg-db-1 pg_dumpall -c -U gerg_db_admin > dump.sql

    - name: Copy the database
      ansible.builtin.fetch:
        src: "/home/{{ deployement_user }}/dump.sql"
        dest: "./{{ current_datetime.stdout }}/dump.sql"
        flat: yes

    - name: remove db dump file
      ansible.builtin.file:
        path: "/home/{{ deployement_user }}/dump.sql"
        state: absent

    - name: Copy the medias files
      ansible.posix.synchronize:
        mode: pull
        src: /home/{{ deployement_user }}/gregoirelayet/media/
        dest: "./{{ current_datetime.stdout }}/media"

    - name: Compress files
      community.general.archive:
        path: "./{{ current_datetime.stdout }}/"
        dest: "./gregoirelayet/{{ current_datetime.stdout }}.tar.gz"
      delegate_to: localhost
      become: false

    - name: Remove uncompressed folder
      local_action: ansible.builtin.command rm -r "{{ current_datetime.stdout }}"
      become: false
