---
- name: Provision VPS with everything
  hosts: all
  remote_user: ubuntu
  become: true
  gather_facts: False

- name: Backup vaultwarden
  ansible.builtin.import_playbook: backup-vaultwarden.yaml
