---
- name: Setup services on VPS
  hosts: all
  remote_user: debian
  become: true

  vars_files: vars/main.yaml

  tasks:
      - name: Ensure temp-build directory exists
        become: true
        become_user: "{{ deployement_user }}"
        ansible.builtin.file:
            path: /home/{{ deployement_user }}/temp-build/gregoirelayet/
            state: directory
            modification_time: preserve
            owner: "{{ deployement_user }}"
            group: "{{ deployement_user }}"
            mode: "0755"

      - name: Copy project code
        become: true
        become_user: "{{ deployement_user }}"
        ansible.posix.synchronize:
            src: "{{ playbook_dir | dirname }}/"
            dest: "/home/{{ deployement_user }}/temp-build/gregoirelayet/"
            use_ssh_args: true
            recursive: true
            archive: false
            checksum: true
            delete: true
            times: false
            rsync_path: "sudo rsync"
            rsync_opts:
                - "--chown={{ deployement_user }}:{{ deployement_user }}"
                - "--exclude=__pycache__/"
                - "--include=src"
                - "--include=src/***"
                - "--exclude=src/static_root/"
                - "--exclude=src/static_build/"
                - "--include=Dockerfile"
                - "--include=Pipfile"
                - "--include=Pipfile.lock"
                - "--include=entrypoint.sh"
                - "--include=.dockerignore"
                - "--exclude=*"
        notify:
            - Rebuild and restart gregoirelayet docker images

  handlers:
      - name: Rebuild and restart gregoirelayet docker images
        ansible.builtin.include_tasks: handlers-tasks/restart-gl-service.yaml
