---
- name: Provision VPS with everything
  hosts: all
  remote_user: ubuntu
  become: true

- name: Setup server
  ansible.builtin.import_playbook: setup-server.yaml

# - name: Build website
#   ansible.builtin.import_playbook: build-website.yaml

- name: Setup services
  ansible.builtin.import_playbook: setup-services.yaml

- name: Deploy ssg
  ansible.builtin.import_playbook: deploy-ssg.yaml