---
- name: Provision VPS with security settings and docker
  hosts: all
  remote_user: ubuntu
  become: true

  vars_files: vars/main.yaml

  tasks:
    - name: Secure server
      ansible.builtin.include_role:
        name: geerlingguy.security

    - name: Enable firewall
      ansible.builtin.import_tasks: tasks/firewall.yaml

    - name: Create deployement user
      ansible.builtin.import_tasks: tasks/create_user.yaml

    - name: Install acl
      ansible.builtin.apt:
        name: acl
        state: present


    - name: Install docker
      ansible.builtin.include_role:
        name: geerlingguy.docker

    - name: Log into DockerHub
      become: true
      become_user: "{{ deployement_user }}"
      vars:
        docker_hub_pwd: "{{ lookup('file', './docker-hub-token') }}"
      community.docker.docker_login:
        username: gregggg
        password: "{{ docker_hub_pwd }}"
        timeout: 120
