---
- name: Seting up services using docker compose
  hosts: all
  remote_user: debian
  become: true

  tasks:
      - name: Copy configs files
        ansible.builtin.copy:
            src: ./configs
            dest: /home/{{ deployement_user }}/
            owner: "{{ deployement_user }}"
            group: "{{ deployement_user }}"
            mode: "0644"
        notify:
            - Restart docker-compose

  handlers:
      - name: Restart docker-compose
