---
- name: Seting up services using docker compose
  hosts: all
  remote_user: ubuntu
  become: true

  vars_files: vars/main.yaml

  tasks:
    - name: Ensures all necessary docker bind directory exists
      ansible.builtin.file:
        path: /home/{{ deployement_user }}/{{ item.dir }}
        state: directory
        modification_time: preserve
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      loop:
        - {
            dir: "caddy-data",
            owner: "{{ deployement_user }}",
            group: "{{ deployement_user }}",
            mode: "755",
          }
        - {
            dir: "gregoirelayet/ssg",
            owner: "1000",
            group: "1000",
            mode: "755",
          }
        - {
            dir: "vw-data",
            owner: "{{ deployement_user }}",
            group: "{{ deployement_user }}",
            mode: "755",
          }

    - name: Copy configs files
      ansible.builtin.copy:
        src: ./configs/
        dest: /home/{{ deployement_user }}/
        owner: "{{ deployement_user }}"
        group: "{{ deployement_user }}"
        mode: "0600"
      notify:
        - Restart all docker-compose services


  handlers:
    - name: Restart all docker-compose services
      ansible.builtin.include_tasks: handlers-tasks/restart-all-services.yaml
