---
- name: Provision VPS with security settings and docker
  hosts: all
  remote_user: debian
  become: true

  vars_files: vars/main.yaml

  tasks:
    - name: Create deployement user
      ansible.builtin.import_tasks: tasks/create_user.yaml

    - name: Install acl
      ansible.builtin.apt:
        name: acl
        state: present

    # - name: Secure server
    #   ansible.builtin.include_role:
    #     name: geerlingguy.security

    # - name: Enable firewall
    #   ansible.builtin.import_tasks: tasks/firewall.yaml

    - name: Install docker
      ansible.builtin.include_role:
        name: geerlingguy.docker
    
    - name: Log into DockerHub
      become_user: "{{deployement_user}}"
      vars:
        docker_hub_pwd: "{{ lookup('file', './docker-hub-token') }}"
      community.docker.docker_login:
        username: gregggg
        password: "{{docker_hub_pwd}}"
        timeout: 120
        debug: yes
      
