---
- name: Setup services on VPS
  hosts: all
  remote_user: debian
  become: true

  vars_files: vars/main.yaml

  tasks:
      - name: Copy project code
        become: true
        become_user: "{{ deployement_user }}"
        ansible.posix.synchronize:
            src: ../
            dest: "/home/{{ deployement_user }}/temp-build/gregoirelayet/"
            rsync_opts:
                - "--exclude=*"
                - "--include=src/"
                - "--include=Dockerfile"
                - "--include=Pipfile"
                - "--include=Pipfile.lock"
                - "--include=entrypoint.sh"
                - "--include=.dockerignore"
                - "--exclude=static_root/"
                - "--exclude=static_build/"
                - "--exclude=__pycache__/"
        notify:
            - regoirelayet docker build
