# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-24.04"
  

  config.dns.tld = "test"
  config.vm.hostname = "gregoirelayet"

  config.dns.patterns = [/^(\w+\.)*gregoirelayet\.test$/]

  config.vm.network :private_network, ip: "192.168.56.69"


  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
  
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
    vb.cpus = 1

    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end


  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yaml"
    ansible.compatibility_mode = "2.0"
  end
end
