---
- name: Add a deployment user
  user:
    name: "{{ deployement_user }}"
    shell: /usr/sbin/nologin
    state: present


- name: Add sudo rights for deployment user
  lineinfile:
    dest: /etc/sudoers
    regexp: "^{{ deployement_user }}"
    line: "{{ deployement_user }} ALL=(ALL) NOPASSWD: ALL"
    state: present
    validate: "visudo -cf %s"