# Generated by Django 5.0.3 on 2024-06-20 09:43

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_homepage_passions_alter_homepage_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', wagtail.fields.StreamField([('Page', wagtail.blocks.PageChooserBlock(can_choose_root=True))])),
                ('github_link', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
