# Generated by Django 5.0.3 on 2024-06-25 20:34

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_footer_github_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Header",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pages",
                    wagtail.fields.StreamField(
                        [
                            (
                                "Page",
                                wagtail.blocks.PageChooserBlock(can_choose_root=True),
                            )
                        ]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
