# Generated by Django 5.0.3 on 2024-07-11 17:36

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_header"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage",
            old_name="passions",
            new_name="other_passions",
        ),
        migrations.RenameField(
            model_name="homepage",
            old_name="timeline",
            new_name="experiences",
        ),
    ]
