# Generated by Django 5.0.3 on 2024-07-11 17:49

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_rename_passions_homepage_other_passions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="experiences",
            field=wagtail.fields.StreamField(
                [
                    (
                        "Experience",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                ("year", wagtail.blocks.CharBlock()),
                                ("description", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        ),
    ]
