# Generated by Django 5.0.7 on 2024-08-07 09:44

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0095_embed"),
        ("website", "0009_alter_homepage_experiences"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("body", wagtail.fields.RichTextField(verbose_name="Corps de la page")),
            ],
            options={
                "verbose_name": "Static page to use for legals pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
