# Generated by Django 5.0.7 on 2024-07-25 10:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_blogtag_locale_alter_blogtag_translation_key_and_more"),
        ("wagtailcore", "0095_embed"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpagetag",
            name="locale",
            field=models.ForeignKey(
                default="",
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogpagetag",
            name="translation_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name="blogpagetag",
            unique_together={("translation_key", "locale")},
        ),
    ]
