# Generated by Django 5.0.7 on 2024-07-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_alter_blogtag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogtag",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=100, verbose_name="slug"
            ),
        ),
    ]
